### ISSUE TITLE
undefined local variable or method `inbox_path'

### ISSUE THREAD

**Issue by carsor007** [ziko07/social_sharetribe#1]
Receiving error message below when a user that is not logged in  clicks on a username that posted the listing.

The profile page only shows up if they are logged in. How can I redirect users that click on a username to be redirected to a login/registration page?

www.marketplace.sharetribe.com/en/myusername -- > will only take them to the profile page if they are logged into the marketplace. Otherwise it throws a marketplace not available error message.

```
ActionView::Template::Error (undefined local variable or method `inbox_path' for #<#<Class:0x007f5e8e43c710>:0x007f5e8fdee348>):
           <a href="#">Notifications<span class="<%= get_badge_class(@person.friends.count) %>"><%= @person.friends.count %></span></a>
           </li>
    <li>
      <a href="<%= inbox_path %>" class="<%= 'active' if action_name == 'show' && controller_name == 'inboxes' %>">Messages
     14:         <span class="<%= get_badge_class(@person.friends.count) %>"><%= unread_count %></span></a>
     15:     </li>
     16:     <li>
   app/views/social/_social_nav.html.erb:13:in `_app_views_social__social_nav_html_erb__4237919624931205881_70022054441920'
   app/views/layouts/social.html.erb:65:in `_app_views_layouts_social_html_erb___2249255753954774039_70022045433980'
   app/controllers/people_controller.rb:68:in `show'
   lib/rack_middleware/current_marketplace_appender.rb:13:in `call'
   lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
   lib/rack_middleware/enforce_ssl.rb:23:in `call'
 
 
 Processing by ErrorsController#server_error as HTML
   Parameters: {"locale"=>"en", "username"=>"eve"}
  Rendered errors/status_500.haml within layouts/blank_layout (1.3ms)
 Completed 500 Internal Server Error in 52ms (Views: 8.1ms | ActiveRecord: 34.3ms)

```

routes.rb has 

 ```
get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")

...............................................................................................

 resource :inbox, :only => [:show]

        resources :messages, :controller => :conversations do
          collection do
            get :received, to: 'inboxes#show'

```

**Comment by ziko07** [comment]
Issue solved.
